site_name: LLMs on LLMs
site_url: https://bydanielrosehill.com/llms-on-llms/
theme:
  name: material 
nav:
  - Home: index.md
plugins:
  - gen_nav:
      enabled: true
  - search
 

not_in_nav: |
  images/