#!/bin/bash

# Define the directory to search
DIRECTORY="/home/daniel/Git/llms-on-llms/docs"

# Define the correct footer text (escaped for use in sed)
FOOTER_TEXT="*The above text was generated by a large language model (LLM) and its accuracy has not been validated. This page is part of 'LLMs-on-LLMs,' a Github repository by Daniel Rosehill which explores how curious humans can use LLMs to better their understanding of LLMs and AI. However, the information should not be regarded as authoritative and given the fast pace of evolution in LLM technology will eventually become deprecated. This footer was added at 16-Nov-2024.*"

# Step 1: Find files where the footer exists but without surrounding "---"
find "$DIRECTORY" -name "*.md" -exec bash -c '
if grep -q "$FOOTER_TEXT" "$1" && ! grep -q "^---$" "$1"; then
    # Step 2: Add "---" before and after the footer
    sed -i "/$FOOTER_TEXT/i ---" "$1"
    sed -i "/$FOOTER_TEXT/a ---" "$1"
fi' _ {} \;