import os
from datetime import datetime

def append_footer_to_markdown_files(base_directory):
    # Get today's date in dd-mm-yyyy format
    today_date = datetime.now().strftime('%d-%m-%Y')
    
    # Footer text with date placeholder replaced
    footer = f'''
---

The above text was generated by a large language model (LLM) and its accuracy has not been validated. This page is part of 'LLMs-on-LLMs,' a Github repository by Daniel Rosehill which explores how curious humans can use LLMs to better their understanding of LLMs and AI. However, the information should not be regarded as authoritative and given the fast pace of evolution in LLM technology will eventually become deprecated. 

This footer was added at {today_date}.
---'''
    
    # Walk through the directory
    for root, dirs, files in os.walk(base_directory):
        for file in files:
            # Check if file is a markdown file and not named index.md
            if file.endswith('.md') and file != 'index.md':
                full_path = os.path.join(root, file)
                
                # Read the existing content
                with open(full_path, 'r', encoding='utf-8') as f:
                    content = f.read()
                
                # Check if footer is already present to avoid duplication
                if footer.strip() not in content:
                    # Append footer to the file
                    with open(full_path, 'a', encoding='utf-8') as f:
                        f.write(footer)
                    print(f"Added footer to {full_path}")
                else:
                    print(f"Footer already exists in {full_path}, skipping.")

# Hard-code your base directory path here
base_directory = '/home/daniel/Git/llms-on-llms/outputs/by-topic'

# Call the function with the specified path
append_footer_to_markdown_files(base_directory)

print("Script has finished processing markdown files.")