name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - published

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout published
        uses: actions/checkout@v2

      # Step 2: Deploy MkDocs to GitHub Pages
      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REQUIREMENTS: deploy/requirements.txt  # Use GITHUB_TOKEN for authentication